# Generated by Django 5.2.2 on 2025-06-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jegyzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=200, verbose_name='Cím')),
                ('tartalom', models.TextField(verbose_name='Tartalom')),
                ('kategoria', models.CharField(max_length=50, verbose_name='Kategória')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás dátuma')),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_task.jegyzetelosfelhasznalo')),
            ],
            options={
                'verbose_name': 'Jegyzet',
                'verbose_name_plural': 'Jegyzetek',
                'ordering': ['-datum'],
            },
        ),
    ]
